# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd7e2ac3517e9f2ff6decf3b2cf9e0f58d15ab9964695596fae4f7dac87af78fe26c8812f3e48b8cefeb8ab5674300f94eedcde79dfc9938e5098ff9c39a3ef3

test:
  secret_key_base: b69a17928abb302d286661aa932e9e0c6c2ee3f821c14d76eda547139e3d027138ccb1ca1b0537b09447ad495276eda07ec98f5451e34d94ff3ceb8e1e2bfcea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
